### ISSUE TITLE
contao-manager-plugin support for /src in main composer.json

### ISSUE THREAD

**Issue by gebi84** [contao/manager-plugin#12]
It would be nice to also scan for 'contao-manager-plugin' in extra in the main composer.json and not only in the installed.json.

my quick workaround was:

```php
#/vendor/contao/manager-plugin/src/PluginLoader.php:160`
$json = json_decode(file_get_contents(__DIR__.'/../../../../composer.json'), true);
if (isset($json['extra']['contao-manager-plugin'])) {
	if (!class_exists($json['extra']['contao-manager-plugin'])) {
		throw new \RuntimeException(
			sprintf('Plugin class "%s" not found', $json['extra']['contao-manager-plugin'])
		);
	}

	$plugins[$json['name']] = new $json['extra']['contao-manager-plugin']();
}
```

my Code lives in ROOT/src/VENDOR/BUNDLE
my composer.json:
```json
"autoload": {
	"psr-4": { "VENDOR\\BUNDLE\\": "src/VENDOR/BUNDLE/" }
}
```

Or am I wrong?

**Comment by aschempp** [comment]
Imho there is no need for that. You can simply add a `ContaoManagerPlugin` class to the global namespace and it will be loaded automatically. See https://docs.contao.org/books/extending-contao4/managed-edition/#adding-a-manager-plugin

**Comment by gebi84** [comment]
Thx i will try that later

... works perfekt thank you.
