### ISSUE TITLE
Error in YamlFileLoader

### ISSUE THREAD

**Issue by rabauss** [contao/manager-plugin#15]
Since we have updated from version 2.2.1 to 2.3.1 in c4.4 our continous delivery throws an error with our own extension.
There are called some commands `contao:install-web-dir` > `cache:clear` > `cache:warmup` and then the following error occurs:

```
In YamlFileLoader.php line 704:
                                                                               
  There is no extension able to load the configuration for "bwein_contao_extension" (in /var/www/vhosts/xxx/app/config/parameters.yml). Looked for namespace "bwein_contao_extension", found none      
```    

what did you change with the new version? and how can we fix this in our own extension?
our own extension should be loaded after contao-core-bundle and has own configuration-parameters...

**Comment by leofeyer** [comment]
Please run `composer run-script post-install-cmd` and see if it fixes your issue. Otherwise please post the output here.

**Comment by aschempp** [comment]
How did you load the bundle in your Contao Managed Edition?

**Comment by rabauss** [comment]
We did `composer update` on local console and on deploy we just run `composer install  --no-scripts`.
Obviously then some command were missing for:
```
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
```
Now we changed back to `composer run-script post-install-cmd` via contao-manager.phar - because in the past we had problems with corrupted composer.phar of the server...
It's working again.
