### ISSUE TITLE
File .ini cannot be decoded 

### ISSUE THREAD

**Issue by DVeris** [contao/manager-plugin#21]
https://github.com/contao/manager-plugin/blob/841a378dce34a72ed5eb1056b784bca8e7f09abc/src/Bundle/Parser/IniParser.php#L91
`$ini = parse_ini_string(file_get_contents($file));`

more universal?

**Comment by aschempp** [comment]
Fixed in 8ae14647fcafc83ab1c5394aeb0f999c4a7f2f14
