### ISSUE TITLE
Update for Composer v2

### ISSUE THREAD

**Issue by Toflar** [contao/manager-plugin#24]
See https://github.com/composer/composer/issues/8726

**Comment by aschempp** [comment]
I have added experimental support in https://github.com/contao/manager-plugin/commit/47e06ef5239dafd4a9578024d2881f07ba4773df

To resolve the `composer.json` locally (and get composer v2) 
- Add `"composer/semver": "^2.0@dev"`
- Remove `friendsofphp/php-cs-fixer` as it is no compatible with `semver` v2
