### ISSUE TITLE
Composer-Error mit der Version 2.10.0

### ISSUE THREAD

**Issue by srhinow** [contao/manager-plugin#31]
Nach dem eine Contao-Installation (4.4) der Contao-Mnager auf die Version 2.10.0 aktualisiert wurde, erscheint beim initialisieren ein Fehler.

![grafik](https://user-images.githubusercontent.com/741418/90497686-a5465900-e147-11ea-9635-83566355761f.png)

Ich habe das vorübergehend die 2.10.0 in conflicts in der composer.json gepackt.

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/manager-plugin/issues/30
