### ISSUE TITLE
Incompatibility with Contao 5

### ISSUE THREAD

**Issue by fritzmg** [contao/manager-plugin#48]
Currently the `contao/manager-plugin` is only unlocked for up to Symfony 5. However there is a bug with `symfony/web-profiler-bundle` (see https://github.com/symfony/symfony/pull/46650). While this fixed in version `6.1.2` of `symfony/web-profiler-bundle` the new version now requires version `^6.0` of `symfony/http-kernel`. Thus version `6.1.2` cannot be installed in Contao 5 as `contao/manager-plugin` still has a maximum dependency of `^5.0` on `symfony/http-kernel`.

**Comment by m-vo** [comment]
We could still add a conflict on `"symfony/web-profiler-bundle": ">=6.0, <6.1.2"` which has the problem of the wrong/missing dependency.
