### ISSUE TITLE
PluginLoader can't load Plugin from AppBundle

### ISSUE THREAD

**Issue by Serhii-DV** [contao/manager-plugin#5]
The problem. I need to use custom `routing.yml`. According to [this documentation](https://docs.contao.org/books/extending-contao4/managed-edition/plugins.html) for doing this I have to create `Plugin` in my `AppBundle` and add as `contao-manager-plugin` to `composer.json`. But, `PluginLoader` doesn't load it because it loads plugins only from `installed.json` file. In another words, it loads plugins from installed packages, not from `AppBundle`.

**Comment by aschempp** [comment]
The information you are mentioning is about adding a plugin to your Composer package. For customizing the application, please check https://docs.contao.org/books/extending-contao4/managed-edition/#adding-a-manager-plugin
