### ISSUE TITLE
Deprecate the JSON parser

### ISSUE THREAD

**Issue by leofeyer** [contao/manager-plugin#6]
IMO we should encourage people to primarily use the `ContaoManager\Plugin` class to register bundles, routes and configuration, therefore we should deprecate the JSON parser and the `bundles.json` file. Most people don't use a `bundles.json` file anyway.

@contao/developers What do you think?

**Comment by Toflar** [comment]
And they shouldn't because I'm not sure if opcode can optimize this. If you are returning a regular key value array I'm pretty sure opcode can improve speed there so I'm all in for that deprecation.

**Comment by aschempp** [comment]
fine with me. We just need the ini parser for legacy extensions.

**Comment by leofeyer** [comment]
Deprecated in b8f567760289f10701f334f8f907217f8452ed8a.
